- Salva todos os registros em beckup
- Salva todos os registros nas demais tabelas
- Se existir dados na tabela de beckup, criar um objeto com a última data de atualização
- enviar esse objeto para o servidor
- Receber um outro objeto com novos dados
- Salvar localmente atualizando a tabela tabela de beckup e a própria